version: '3.8'

services:
  frontend:
    container_name: ws_frontend
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./frontend:/usr/share/nginx/html
  backend:
    container_name: ws_backend
    build: ./backend
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - './backend/:/app'
      - '/app/node_modules'