version: '3.8'

services:
  frontend:
    container_name: ws_frontend
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./frontend:/usr/share/nginx/html
  backend:
    container_name: ws_backend
    image: node:alpine
    entrypoint: /app/entrypoint.sh
    command: npm start -- ${FISHGAME_INTERFACE}
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: "true"
    volumes:
      - './backend/:/app'
